name: Contracts CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - '**'

env:
  NODE_OPTIONS: --max_old_space_size=5120

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn
        run: npm install -g yarn
      - run: ls -lah ./abi/contracts/**/*
      - run: yarn
      - run: yarn build
      - name: Run contract tests
        run: yarn test
      - name: Run contract coverage
        run: yarn coverage
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
      - name: Run Forge tests
        run: |
          forge test -vvv --ffi
