name: Contract CD

on:
  release:
    types:
      - created

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn 
      - run: yarn build
      - name: Run contract tests
        run: yarn test
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
  build_and_deploy:
    name: Build and Deploy
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn 
      - run: yarn build
      - name: Deploy contract to Rinkeby
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: npx hardhat deploy-ci --network rinkeby
      - name: Look here for contract info
        run: |
          echo "Contract deployed on Rinkeby to `cat logs/deploy.json| jq -r '.contractAddresses'`"
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
